name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    - imageio==2.1.2
    - pip:
        - moviepy
        - tensorflow==1.1
	   - backports.shutil-get-terminal-size==1.0.0
        - et-xmlfile==1.0.1
        - ipython-genutils==0.2.0
        - jupyter-client==5.0.1
        - jupyter-console==5.1.0
        - jupyter-core==4.3.0
        - prompt-toolkit==1.0.14
        - protobuf==3.3.0
        - rope-py3k==0.9.4.post1
        - tables==3.3.0
        - tensorflow-gpu==1.1.0
        - moviepy
        - pygame
